apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "scaler.name" . }}-role
rules:
  - apiGroups: ["apps"]
    resources:
    - "deployments"
    - "deployments/status"
    verbs:
    - "get"
    - "patch"
    - "list"