apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "scaler.name" . }}-sa-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ template "scaler.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "scaler.name" . }}-role
  apiGroup: rbac.authorization.k8s.io